services:
  - type: web
    name: job-pilot-server
    env: node
    plan: free
    region: ohio
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: PORT
        fromService:
          type: web
          name: job-pilot-server
          property: port
      - key: CLIENT_URL
        value: https://job-pilot-client.vercel.app