services:
  - type: web
    name: job-pilot-server
    env: node
    plan: free
    region: ohio
    buildCommand: npm install --production=false && npx tsc --skipLibCheck
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: job-pilot-server
          property: port
      - key: CLIENT_URL
        value: https://job-pilot-client.vercel.app